[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-ml-lab"
version = "0.1.0"
description = "Hands-on AI/ML systems and architecture experiments"
authors = [{name="Pradeep"}]
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scikit-learn",
    "matplotlib",
]

[tool.setuptools.packages.find]
where = ["src"]

