name: Python CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Weather CLI dependencies
        working-directory: weather-cli
        run: |
          pip install -r requirements.txt

      - name: Install Stats Visualizer dependencies
        working-directory: stats-visualizer
        run: |
          pip install -r requirements.txt || true

      - name: Run tests
        run: |
          pytest weather-cli/tests stats-visualizer/tests -vv
